export default {
  SET_COMMENTS_RATES: 'SET_COMMENTS_RATES',
  ASYNC_COMMENT_RATE_REQUEST_START: 'ASYNC_COMMENT_RATE_REQUEST_START',
  ASYNC_COMMENT_RATE_REQUEST_FAILURE: 'ASYNC_COMMENT_RATE_REQUEST_FAILURE',
  ASYNC_COMMENT_RATE_REQUEST_SUCCESS: 'ASYNC_COMMENT_RATE_REQUEST_SUCCESS',
}
